package FS;


/**
* FS/FileSystemHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSystem.idl
* Sábado, 11 de Novembro de 2017 16h10min08s BRT
*/

abstract public class FileSystemHelper
{
  private static String  _id = "IDL:FS/FileSystem:1.0";

  public static void insert (org.omg.CORBA.Any a, FS.FileSystem that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static FS.FileSystem extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (FS.FileSystemHelper.id (), "FileSystem");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static FS.FileSystem read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_FileSystemStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, FS.FileSystem value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static FS.FileSystem narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FS.FileSystem)
      return (FS.FileSystem)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      FS._FileSystemStub stub = new FS._FileSystemStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static FS.FileSystem unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FS.FileSystem)
      return (FS.FileSystem)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      FS._FileSystemStub stub = new FS._FileSystemStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
