package FS;


/**
* FS/FileSystem.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSystem.idl
* Sábado, 11 de Novembro de 2017 16h10min08s BRT
*/

public interface FileSystem extends FileSystemOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FileSystem
