package FS;


/**
* FS/FileSystemOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSystem.idl
* Sábado, 11 de Novembro de 2017 16h10min08s BRT
*/

public interface FileSystemOperations 
{
  int create (String fileName);
  int delete (String fileName);
  int copy (String fileName, String newFileName);
  int write (String fileName, String text);
  int read (String fileName, org.omg.CORBA.StringHolder text);
  void shutdown ();
} // interface FileSystemOperations
