package FS;


/**
* FS/FileSystemPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileSystem.idl
* Sábado, 11 de Novembro de 2017 16h10min08s BRT
*/

public abstract class FileSystemPOA extends org.omg.PortableServer.Servant
 implements FS.FileSystemOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("create", new java.lang.Integer (0));
    _methods.put ("delete", new java.lang.Integer (1));
    _methods.put ("copy", new java.lang.Integer (2));
    _methods.put ("write", new java.lang.Integer (3));
    _methods.put ("read", new java.lang.Integer (4));
    _methods.put ("shutdown", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // FS/FileSystem/create
       {
         String fileName = in.read_string ();
         int $result = (int)0;
         $result = this.create (fileName);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // FS/FileSystem/delete
       {
         String fileName = in.read_string ();
         int $result = (int)0;
         $result = this.delete (fileName);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 2:  // FS/FileSystem/copy
       {
         String fileName = in.read_string ();
         String newFileName = in.read_string ();
         int $result = (int)0;
         $result = this.copy (fileName, newFileName);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 3:  // FS/FileSystem/write
       {
         String fileName = in.read_string ();
         String text = in.read_string ();
         int $result = (int)0;
         $result = this.write (fileName, text);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 4:  // FS/FileSystem/read
       {
         String fileName = in.read_string ();
         org.omg.CORBA.StringHolder text = new org.omg.CORBA.StringHolder ();
         int $result = (int)0;
         $result = this.read (fileName, text);
         out = $rh.createReply();
         out.write_long ($result);
         out.write_string (text.value);
         break;
       }

       case 5:  // FS/FileSystem/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:FS/FileSystem:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public FileSystem _this() 
  {
    return FileSystemHelper.narrow(
    super._this_object());
  }

  public FileSystem _this(org.omg.CORBA.ORB orb) 
  {
    return FileSystemHelper.narrow(
    super._this_object(orb));
  }


} // class FileSystemPOA
